name: Docs Update

on:
  push:
    branches:
      - master


jobs:
  style:
    name: Docs Update
    runs-on: ubuntu-latest
    if: github.repository == 'royerlab/aydin'

    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r docs/requirements-docs.txt
      - name: Build docs
        run: |
          make clean
          make html
      - name: Update doc
          run: |
            make clean
            make html
