name: Fedora-build

on: [push]

jobs:
  fedora-build:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          sudo dnf install curl -y
          curl --output anaconda.sh https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
          chmod +x anaconda.sh
          bash anaconda.sh
          conda init bash
      - name: Install dependencies
        run: |
          python -V
          pip3 --version
          pip --version
          python3.9 -m pip install --upgrade pip
          sudo -H pip install -e .
          sudo -H pip install -r requirements/development.txt
          sh build/linux/build.sh
