name: Fedora-build

on: [push]

jobs:
  fedora-build:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          dnf install python3.9 -y
          dnf install python3-pip -y
          echo All going well till this point
          python3.9 -V
      - name: Install dependencies
        run: |
          ls
          python3.9 -V
          python -V
          pip3 install -e .
          pip3 install -r requirements/development.txt
          sh build/linux/build.sh
