name: Fedora-build

on: [push]

jobs:
  fedora-build:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          which python
          which python3
        name: Run in container
