name: Fedora-build

on: [push]

jobs:
  fedora-build:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - name: Run in container
        run: |
          dnf install python3.9 -y
          # dnf install python3-pip -y
          echo All going well till this point
          python3.9 -V
      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          pip install -e .
