name: Fedora-build

on: [push]

jobs:
  fedora-build:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          dnf remove python3
          dnf install python3.9 -y
          dnf install python3-pip -y
          echo All going well till this point
          python3.9 -V
      - name: Install dependencies
        run: |
          ls
          python3.9 -V
          pip3 --version
          pip --version
          python3.9 -m pip install --upgrade pip
          sudo -H pip install -e .
          sudo -H pip install -r requirements/development.txt
          sh build/linux/build.sh
